### PR TITLE
Update revision for FACE project

### PR DESCRIPTION
**Pull request by jvdp1**
## Issue
The current commit of FACE in the fpm.toml refers to a version not compatible with the latest fpm.

## Proposed solution
Update the commit of FACE in the fpm.toml

### CODE REVIEW

**Comment by jvdp1** [comment]
Fixes #105

**Comment by szaghi** [comment]
@jvdp1 
Thank you very much for the PR.

Can you sign your commits? 

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

I am using signed commits as a more safe versioning approach, thus unsigned commits are no longer "mergeable".

**Comment by jvdp1** [comment]
Thank you @szaghi . It is done.

**Comment by szaghi** [comment]
@jvdp1 Thank you very much!

**Pull request merged**
